server:
  port: 8090

spring:
  mvc:
    favicon:
      enabled: false

udpServer:
  port: 4000

application:
  title: ${name}
  version: ${version}

management:
  endpoints:
    web:
      exposure:
        include: metrics

